import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import { archiveHeader } from "../archive.js";
import { buildHugoSiteContent } from "./build-content.js";

test("site content build generates deterministic data and preserves the handwritten index", async () => {
  const repoRoot = await mkdtemp(join(tmpdir(), "aeb-site-content-"));
  try {
    await mkdir(join(repoRoot, "src"), { recursive: true });
    await mkdir(join(repoRoot, "docs/questions"), { recursive: true });
    await mkdir(join(repoRoot, "site/content/questions"), { recursive: true });
    await writeFile(
      join(repoRoot, "src/live-stream-list.md"),
      `${archiveHeader}\n- [Live Stream #1: Example](https://www.youtube.com/watch?v=abcdefghijk) \`1-example\`\n`,
      "utf8",
    );
    await writeFile(
      join(repoRoot, "docs/questions/1-example-questions.md"),
      [
        "# Example questions",
        "",
        "Time links open the YouTube video at the relevant timestamp.",
        "",
        "| Time | Question | Short answer / answer direction | Expanded answer |",
        "|---|---|---|---|",
        "| <a href=\"https://youtu.be/abcdefghijk?t=62\" target=\"_blank\" rel=\"noopener noreferrer\">1:02</a> | What was the example? | A short answer. | A supported expanded answer. |",
        "",
      ].join("\n"),
      "utf8",
    );
    await writeFile(join(repoRoot, "site/content/questions/_index.md"), "handwritten\n", "utf8");
    await writeFile(join(repoRoot, "site/content/questions/stale.md"), "stale\n", "utf8");

    const messages: string[] = [];
    const summary = await buildHugoSiteContent({
      repoRoot,
      buildSearchIndex: false,
      logger: (message) => messages.push(message),
    });

    assert.deepEqual(summary, {
      generatedPageCount: 1,
      numberedPageCount: 1,
      specialPageCount: 0,
      descriptionOverrideCount: 0,
      questionRowCount: 1,
    });
    assert.equal(await readFile(join(repoRoot, "site/content/questions/_index.md"), "utf8"), "handwritten\n");
    await assert.rejects(readFile(join(repoRoot, "site/content/questions/stale.md"), "utf8"), /ENOENT/u);

    const page = await readFile(join(repoRoot, "site/content/questions/1-example-questions.md"), "utf8");
    assert.match(page, /description_source: 'generated_from_questions'/u);
    assert.match(page, /Generated by npm run build:site-content from docs\/questions\/1-example-questions\.md/u);
    const episodes = JSON.parse(await readFile(join(repoRoot, "site/data/episodes.json"), "utf8")) as unknown[];
    const questions = JSON.parse(await readFile(join(repoRoot, "site/data/questions.json"), "utf8")) as unknown[];
    assert.equal(episodes.length, 1);
    assert.deepEqual(questions, [{
      episode_number: 1,
      episode_title: "Example",
      question_page: "questions/1-example-questions.md",
      content_path: "questions/1-example/",
      time_label: "1:02",
      start_seconds: 62,
      video_url: "https://youtu.be/abcdefghijk?t=62",
      question: "What was the example?",
      short_answer: "A short answer.",
      expanded_answer: "A supported expanded answer.",
      row_index: 1,
      is_numbered: true,
      is_special: false,
      search_text: "1 example what was the example? a short answer. a supported expanded answer.",
    }]);
    assert.ok(messages.includes("Question rows: 1"));
  } finally {
    await rm(repoRoot, { recursive: true, force: true });
  }
});
